### PR TITLE
Add lab testing and data minimization profiles, update prose

### PR DESCRIPTION
**Pull request by masnick**
This PR makes a number of updates throughout the IG, including:

- Adding in the data minimization profiles
- Adding profiles for lab testing results
- Rewriting `index.md` to include the data minimization profiles and generally clarify the documentation
- Splits out some content into `conformance.md` to keep `index.md` reasonably short
- Adds custom Liquid templates to clean up the rendering of examples
- Adds `id` back into Bundle examples, and fixes the structure of the references. The former change is needed to get clean builds from publisher.jar as the errors caused by missing `id` could not be suppressed. We can revisit this later.
- Changes the recommended id format from `resource:0` to `r:0` to save bytes.

I'd like to get a few other sets of eyes on this before I merge in, if possible. Please defer comments on specific elements until after we get the overall PR merged in. Thanks!

### CODE REVIEW

**Comment by jmandel** [comment]
> Changes the recommended id format from resource:0 to r:0 to save bytes.

Have you looked at the impact of this on the compressed payloads? My experience has been that these sorts of text changes have limited impact, but it's worth quantifying. (There is an existing `resource:` URI scheme at least in some nebulous status, FWIW.)

**Comment by jmandel** [comment]
To check the logic on data minimization profiles: how come birthDate is MS but not `1..1`? I think we want to get to "health cards include name + DOB", but we can take this discussion separately.

**Comment by jmandel** [comment]
Shouldn't `Immunization.identifier` and `Immunization.programEligibility` also be profiled out (`0..0`)?

**Comment by isaacvetter** [comment]
Would it be possible to have this PR merged by end of day tomorrow?

**Comment by masnick** [comment]
@isaacvetter yes, we're trying to get all the outstanding PRs merged in today.

**Comment by masnick** [comment]
I captured Josh's two comments above here: https://github.com/dvci/vaccine-credential-ig/projects/2

**Comment by masnick** [comment]
> > Changes the recommended id format from resource:0 to r:0 to save bytes.
> 
> Have you looked at the impact of this on the compressed payloads? My experience has been that these sorts of text changes have limited impact, but it's worth quantifying. (There is an existing `resource:` URI scheme at least in some nebulous status, FWIW.)

I have not looked at the payload difference under compression. Happy to move back to `resource:` if that makes more sense.

**Comment by jmandel** [comment]
Thanks! Let's call it resource for now; we can evaluate this separately from the data minimization profiles.

**Pull request merged**
